apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: tiketing-dev
  artifacts:
    # - image: us.gcr.io/tiketing-dev/auth
    - image: xtophe02/devconnector-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.tsx"
            dest: .
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: xtophe02/devconnector-api-gateway
      context: api-gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: xtophe02/devconnector-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.js"
            dest: .
    # - image: xtophe02/devconnector-users
    #   context: users
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
