apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          # imagePullPolicy: Never
          # image: us.gcr.io/ticketing-dev/auth
          image: xtophe02/devconnector-auth
          env:
            - name: CLOUD_NAME
              value: chrismo
            - name: CLOUD_API_KEY
              value: '891396345568939'
            - name: CLOUD_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: CLOUD_SECRET
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: devconnect
            - name: PORT
              value: '4000'
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  # type: NodePort
  selector:
    app: auth
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: auth
      # nodePort: 31515
