# TO REMOVE AFTER DEPLOYMENY
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-auth-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data'
