apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          # imagePullPolicy: Never
          # image: us.gcr.io/ticketing-dev/auth
          image: xtophe02/devconnector-posts
          env:
            - name: CLOUD_NAME
              value: chrismo
            - name: CLOUD_API_KEY
              value: '891396345568939'
            - name: CLOUD_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: CLOUD_SECRET
            - name: PORT
              value: '4000'
            - name: POSTS_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: posts-mongo-secret
                  key: POSTS_MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  # type: NodePort
  selector:
    app: posts
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: posts
      # nodePort: 31515
