apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          # imagePullPolicy: Never
          # image: us.gcr.io/ticketing-dev/auth
          image: xtophe02/devconnector-users
          env:
            - name: CLOUD_NAME
              value: chrismo
            - name: CLOUD_API_KEY
              value: '891396345568939'
            - name: CLOUD_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: CLOUD_SECRET
            - name: PORT
              value: '4000'
            - name: USERS_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: users-mongo-secret
                  key: USERS_MONGO_URI

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  # type: NodePort
  selector:
    app: users
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: users
      # nodePort: 31515
